### ISSUE TITLE
Merge branch features to Plomino 2

### ISSUE THREAD

**Issue by ivanteoh** [plomino/Plomino#720]
- [ ] #632 ([WIP] Group fields and return field ids with validation errors) Now the PlominoForm is dexterity container.
- [ ] #675 (Fix date validate) Now the date field is text box.
- [ ] #646 (Fix getHidewhenAsJSON) As hidewhen feature is not implemented yet.
- [ ] #644 (Add check for hidden subforms) As hidewhen feature is not implemented yet.
- [ ] #656 (Fix #652 Datagrid has js error)
- [ ] #673 (Dynamic display fields)
- [ ] #642 (Display page forms in read mode)
- [ ] #651 (Search view with nocall)
- [ ] #630 (Fix #625 displayDocument())
- [ ] #628 (Fix #625 Use TemporaryDocument)
